import { Index } from '../enums';

export function getIndexName(symbol: string) {
  const indices = {
    [Index.TAIEX]: '發行量加權股價指數',
    [Index.NonFinance]: '未含金融指數',
    [Index.NonElectronics]: '未含電子指數',
    [Index.NonFinanceNonElectronics]: '未含金融電子指數',
    [Index.Cement]: '水泥類指數',
    [Index.Food]: '食品類指數',
    [Index.Plastic]: '塑膠類指數',
    [Index.CementAndCeramic]: '水泥窯製類指數',
    [Index.PlasticAndChemical]: '塑膠化工類指數',
    [Index.Electrical]: '機電類指數',
    [Index.Textiles]: '紡織纖維類指數',
    [Index.ElectricMachinery]: '電機機械類指數',
    [Index.ElectricalAndCable]: '電器電纜類指數',
    [Index.ChemicalBiotechnologyAndMedicalCare]: '化學生技醫療類指數',
    [Index.Chemical]: '化學類指數',
    [Index.BiotechnologyAndMedicalCare]: '生技醫療類指數',
    [Index.GlassAndCeramic]: '玻璃陶瓷類指數',
    [Index.PaperAndPulp]: '造紙類指數',
    [Index.IronAndSteel]: '鋼鐵類指數',
    [Index.Rubber]: '橡膠類指數',
    [Index.Automobile]: '汽車類指數',
    [Index.Electronics]: '電子工業類指數',
    [Index.Semiconductors]: '半導體類指數',
    [Index.ComputerAndPeripheralEquipment]: '電腦及週邊設備類指數',
    [Index.Optoelectronics]: '光電類指數',
    [Index.CommunicationsTechnologyAndInternet]: '通信網路類指數',
    [Index.ElectronicPartsComponents]: '電子零組件類指數',
    [Index.ElectronicProductsDistirbution]: '電子通路類指數',
    [Index.InformationService]: '資訊服務類指數',
    [Index.OtherElectronics]: '其他電子類指數',
    [Index.BuildingMaterialsAndConstruction]: '建材營造類指數',
    [Index.ShippingAndTransportation]: '航運類指數',
    [Index.Tourism]: '觀光事業類指數',
    [Index.FinancialAndInsurance]: '金融保險類指數',
    [Index.TradingAndConsumerGoods]: '貿易百貨類指數',
    [Index.OilGasAndElectricity]: '油電燃氣類指數',
    [Index.Other]: '其他類指數',
    [Index.TPEX]: '櫃檯指數',
    [Index.TPExTextiles]: '櫃檯紡纖類指數',
    [Index.TPExElectricMachinery]: '櫃檯機械類指數',
    [Index.TPExIronAndSteel]: '櫃檯鋼鐵類指數',
    [Index.TPExElectronic]: '櫃檯電子類指數',
    [Index.TPExBuildingMaterialsAndConstruction]: '櫃檯營建類指數',
    [Index.TPExShippingAndTransportation]: '櫃檯航運類指數',
    [Index.TPExTourism]: '櫃檯觀光類指數',
    [Index.TPExChemical]: '櫃檯化工類指數',
    [Index.TPExBiotechnologyAndMedicalCare]: '櫃檯生技醫療類指數',
    [Index.TPExSemiconductors]: '櫃檯半導體類指數',
    [Index.TPExComputerAndPeripheralEquipment]: '櫃檯電腦及週邊類指數',
    [Index.TPExOptoelectronic]: '櫃檯光電業類指數',
    [Index.TPExCommunicationsAndInternet]: '櫃檯通信網路類指數',
    [Index.TPExElectronicPartsComponents]: '櫃檯電子零組件類指數',
    [Index.TPExElectronicProductsDistribution]: '櫃檯電子通路類指數',
    [Index.TPExInformationService]: '櫃檯資訊服務類指數',
    [Index.TPExCulturalAndCreative]: '櫃檯文化創意業類指數',
    [Index.TPExOtherElectronic]: '櫃檯其他電子類指數',
    [Index.TPExOther]: '櫃檯其他類指數',
  };
  return indices[symbol];
}
